deva_checkpoint: models/deva/DEVA-propagation.pth
key_dim: 64
value_dim: 512
pix_feat_dim: 512
disable_long_term: false
enable_long_term: true
enable_long_term_count_usage: false
max_mid_term_frames: 8
min_mid_term_frames: 5
max_long_term_elements: 2000
num_prototypes: 64
top_k: 20
mem_every: 10
size: 360
amp: true
chunk_size: 1
max_missed_detection_count: 50
max_num_objects: -1
